#
# git-deploy example config
#

# temp is used by some deploy strategies for storing some backup files
temp: "/tmp/git-deploy"
port: 3929
server_name: "janzal"

# enable/disable ui
ui: true
# key-value basic authorization for UI controls
# auth:
#    admin: "123456"

# object of deployed applications
# keys are application identifiers and values are objects containing deployment details
applications:

    BitbucketApp: # app name
        # these three items are only mandatory for deployment
        handler: "bitbucket" # handler - currently is supported only bitbucket and github. If not filled, git-deploy will try to detect handler itself
        strategy: "clone" # there are plenty of strategies, which can be used for deploy. Currently is supported only hardcore
        allow_deployfile: true # if true, .deployfile will be executed

        branches:
            # branch deploy configuration
            master:
                destination: "/Users/janzaloudek/Development/misc/xx/deploy/BitbucketApp/master" # where to deploy application
                # post_deploy and pre_deploy will be executed in context of destination folder
                post_deploy: "ls -la"
                pre_deploy: "ls -la"

            # ...and you can handle multiple branches
            dev:
                destination: "/Users/janzaloudek/Development/misc/xx/deploy/firstApp/dev"
                post_deploy: "ls -la"
                pre_deploy: "ls -la"

            staging:
                destination: "/Users/janzaloudek/Development/misc/xx/deploy/firstApp/staging"

    GithubApp:
       handler: "github"
       strategy: "clone"

       branches:
           master:
               destination: "/Users/janzaloudek/Development/misc/xx/deploy/GithubApp/master"
               post_deploy: "ls -la"
               pre_deploy: "ls -la"
           dev:
               destination: "/Users/janzaloudek/Development/misc/xx/deploy/GithubApp/dev"


