// Generated by CoffeeScript 1.8.0
(function() {
  var BaseHandler;

  BaseHandler = (function() {
    function BaseHandler() {}

    BaseHandler.prototype.extractRepositoryInfo = function() {
      throw new Error('Not implemented yet');
    };

    return BaseHandler;

  })();

  module.exports = BaseHandler;

}).call(this);

//# sourceMappingURL=base-handler.js.map
